/**
 * Avatar Service
 * ==============
 * This module provides functions for avatar management:
 * - Upload avatars to Cloudinary with proper folder structure
 * - Delete avatars from Cloudinary when users remove them
 */

import cloudinary from '../config/cloudinary.js';
import logger from '../middleware/logger.js';
import dotenv from 'dotenv';

/**
 * Upload an avatar file to Cloudinary
 * 
 * @param {Object} file - Multer file object containing:
 *   - buffer: file contents in memory
 *   - mimetype: MIME type (e.g., 'image/jpeg')
 *   - size: file size in bytes
 *   - originalname: original filename from upload
 * 
 * @param {string} userId - MongoDB user ID (used for folder organization)
 * 
 * @returns {Promise<{url: string, publicId: string}>}
 *   - url: The Cloudinary URL for the uploaded image
 *   - publicId: Cloudinary's public ID for future deletion
 * 
 * @throws {Error} If upload fails (network, Cloudinary error, etc.)
 *   Errors are logged but not exposed to frontend (generic message used in controller)
 * 
 * Cloudinary Options:
 * - resource_type: 'image' - strictly images only
 * - folder: `avatars/${userId}` - organized by user for easier management/deletion
 * - public_id: auto-generated by Cloudinary
 * - overwrite: true - if user re-uploads, replace previous avatar
 * - timeout: 60000ms - abort if Cloudinary doesn't respond in 1 minute
 * 
 * OWASP: 
 * - File type already validated in controller
 * - Folder structure allows easy bulk deletion by admin if needed
 * - Overwrite prevents storage bloat from multiple uploads
 */
export const uploadAvatar = async (File, userId) => {
    try {
        if (!file || !file.buffer) {
            throw new Error("Invalid file object: missing buffer");
        }
        if (!userId) {
            throw new Error("User ID is required");
        }
        logger.info(`Starting avatar upload for user ${userId}`);
        
        const uploadPromise = new Promise((resolve, reject) => {
            // Create an upload stream to cloudinary
            const uploadStream = cloudinary.uploader.upload_stream(
                {
                    // Metadata
                    resource_type: 'image', // Image files only
                    folder: `${process.env.APP_NAME}-avatars/${userId}`, // Organize avatars by user ID
                    overwrite: true, // Replace previous avatar if user re-uploads

                    quality: 'auto',
                    fetch_format: 'auto', 
                    timeout: 60000, // 60 Seconds
                    tags: ["avatar", `user_${userId}`],
                    // Return dimensions in response
                    eager: [
                        {
                            width: 200,
                            height: 200,
                            crop: 'fill',
                            quality: 'auto',
                        },
                    ],
                },
                //  Callback when upload completes
                (error, result) => {
                    if (error) {
                        logger.error(`Cloudinary upload error for user ${userId}:`, error.message);
                        reject(error);
                    } else {
                        logger.info(`Avatar uploaded successfully for user ${userId}: ${result.public_id}`);
                        resolve(result);
                    }
                }
            );
            // Connect the file buffer to the upload stream
            uploadStream.end(file.buffer);
        });

        const result = await uploadPromise;

        return {
            url: result.secure_url,
            publicId: result.publicId,
        };
    } catch (error) {
        logger.error(`Failed to upload avatar for user: ${userId}`, error.message);
        throw error;
    }
};

/**
 * Delete an avatar from Cloudinary
 * 
 * @param {string} publicId - Cloudinary's public ID for the file to delete
 *   Example: 'avatars/507f1f77bcf86cd799439011/xyz123'
 * 
 * @returns {Promise<{result: string}>}
 *   - result: 'ok' if deletion succeeded, 'not found' if file doesn't exist
 * 
 * @throws {Error} If deletion fails for other reasons (network, auth, etc.)
 *   Errors are logged but handled gracefully in controller
 * 
 * OWASP:
 * - Deletion is idempotent; deleting a non-existent file returns 'not found' (safe)
 * - Caller must ensure publicId belongs to authenticated user (enforced in controller)
 */
export const deleteAvatar = async (publicId) => {
    try {
        if (!publicId) {
            throw new Error("Public ID is required for deletion");
        }
        logger.info(`Starting avatar deletion for public ID: ${publicId}`);
        
        const result = await cloudinary.uploader.destroy(publicId);
        logger.info(`Avatar deleted successfully: ${publicId} (result: ${result.result}`);

        return result;
    } catch (error) {
        logger.error(`Failed to delete avatar ${publicId}`, error.message)
        throw error;
    }
};

/**
 * Build Cloudinary transformation URL
 * Helper function for constructing optimized URLs at display time
 * 
 * @param {string} publicId - Cloudinary public ID
 * @param {Object} options - Transformation options
 *   - width: desired width in pixels
 *   - height: desired height in pixels
 *   - crop: crop mode ('fill', 'fit', 'scale', etc.)
 *   - quality: quality setting ('auto', 'good', 'best', etc.)
 *   - format: image format ('auto', 'webp', 'jpg', etc.)
 * 
 * @returns {string} Fully transformed Cloudinary URL
 * 
 * Example:
 * buildAvatarUrl('avatars/507f.../xyz123', {width: 200, height: 200, crop: 'fill'})
 * Returns: https://res.cloudinary.com/{CLOUD_NAME}/image/upload/w_200,h_200,c_fill/avatars/507f.../xyz123
 * 
 */
export const buildAvatarUrl = (publicId, options = {}) => {
    if (!publicId) {
        return null;
    }
    const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
    // Transformation string from options
    const transforms = [];
    if (options.width) {
        transforms.push(`w_${options.width}`);
    }
    if (options.height) {
        transforms.push(`h_${options.height}`);
    }
    if (options.crop) {
        transforms.push(`c_${options.crop}`);
    }
    if (options.quality) {
        transforms.push(`q_${options.quality}`);
    }
    if (options.format) {
        transforms.push(`f_${options.format}`);
    }

    const transformString = transforms.length > 0 ? transforms.join(',') : '';

    return `https://res.cloudinary.com/${cloudName}/image/upload/${transformString}${transformString ? '/' : ''}${publicId}`;
};

export default { uploadAvatar, deleteAvatar, buildAvatarUrl };